name:                comonadic-life
version:             0.1.0.0
github:              "marianoheller/comonadic-life"
license:             BSD3
author:              "Mariano Heller"
maintainer:          "marianofheller@gmail.com"
copyright:           "2020 Mariano Heller"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/marianoheller/comonadic-life#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  comonadic-life-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - comonadic-life

tests:
  comonadic-life-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - comonadic-life
